# Generated by Django 3.2.7 on 2021-12-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_anime_temp_atual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='ep_atual',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='temp_atual',
        ),
        migrations.AddField(
            model_name='agenda',
            name='episodio_atual',
            field=models.IntegerField(default=1, verbose_name='Episódio atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agenda',
            name='temporada_atual',
            field=models.IntegerField(default=1, verbose_name='Temporada atual'),
            preserve_default=False,
        ),
    ]
