# Generated by Django 3.2.7 on 2021-12-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211214_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='episodio_atual',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Episódio atual'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='temporada_atual',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Temporada atual'),
        ),
    ]
